# Site settings
title: Software Mercenary
email: zmhot88@126.com
description: As a software develop, Recording is a good habit.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://zmhot88.github.io" # the base hostname & protocol for your site
twitter_username: 
github_username:  zmhot88

# Build settings
markdown: kramdown
